package javaee.spring.test.dao.mybatis;

import javaee.spring.test.entity.People;

public interface IPeopleMybatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    int insert(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    int insertSelective(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    People selectByPrimaryKey(Long id);
    
    People selectByPrimaryKeyByOptimistic(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(People record);
    
    int updateByOptimistic(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(People record);
}